name: artshift
description: 'Aplikasi Pengelolaan Jadwal dan Absensi Keryawan'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Firebase Packages
  firebase_core: ^1.10.0
  firebase_auth: ^3.0.0
  cloud_firestore: ^3.0.0
  google_sign_in: ^5.0.0

  # State Management (BLoC)
  flutter_bloc: ^8.0.0
  equatable: ^2.0.0

  # Other Dependencies
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
